digitalaidseattle/digital-aid-seattle-website

- package-lock.json
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/volunteer.jsx
- styles/global.css
- theme/theme.ts
Initial MUI Theme with styles for palette, typography and button component. 
[Set up primary theme for components](https://app.asana.com/0/0/1204566664333014/f)
|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
| ✓ | :link: Update dependencies |
|     | :scroll: Docs              |
- git pull MuiTemplate
- npm i
- test to ensure typography, palette and buttons are working:
- in volunteer.jsx import mui button and typography `import { Button, Typography } from '@mui/material'
`
- within the return statement include the following code:
```
return (
<Layout>
<Container>
<Button variant='contained'>
Volunteer With Us …
```
> feat: Implement MUI theme with basic styles

- components/CommonHeader.tsx
- components/layouts.tsx
- pages/about_new.tsx
- pages/events_new.tsx
- pages/home_new.tsx
- pages/partners_new.tsx
- pages/projects_new.tsx
- pages/support_us_new.tsx
- pages/volunteers_new.tsx
Add new pages and add the links to the header
Allow rest of the team to develop more quickly
- Create new files under /pages directory, file name matches the path
- Create a mapping between name and the path
- Use Link component in the Header
- Underline when it's the active link
Go to localhost:3000/about_new to see the new header and navigate around it
https://github.com/openseattle/open-seattle-website/assets/1039839/2bb3ea3b-2bb7-43e4-b4a8-4fba054171e6
> Create blank pages navigated by the new Header

- components/CommonFooter.tsx
- components/CommonHeader.tsx
- components/layouts.tsx
Add footer to our common layout
So all pages will have footer!
Because the big and small screen have different order of layout, I created two footer component and display one or another depending on the screensize.
Big screen (desktop)
Smaller screen (phone, 600 width)
> Create common footer

- pages/events_new.tsx
Builds initial Events page.
Needed for new website.
Things to be polished:
- Green bar containing "Events" header should be taller (do we have a defined height for this? This green bar is shared between multiple pages)
- Space between event cards should be increased
- Event cards should be narrower
- Padding around event cards probably needs to be tuned
- Event cards shouldn't be hardcoded; should be pulled from a database or something?
> Initial Events page

- components/cards/CardWithPhoto.tsx
Create Card with Photo Component
Create component for new OpenSeattle website 
Import CardWithPhoto component and test with any page. Save test photo in public folder and pass in string file path to test the component. 
```
import CardProject from 'components/cards/CardOne'
import CardGridContainer from 'components/cards/CardRowContainer'
import CardWithPhoto from 'components/cards/CardWithPhoto'
export default function DynamicPage({ page }) {
return (
<CardGridContainer>
<CardWithPhoto
title="Jeffrey"
description="Program Manager"
image="/jack-finnigan-rriAI0nhcbc-unsplash.jpg"
/>
<CardWithPhoto
title="Jeffrey"
description="Program Manager"
image="/jack-finnigan-rriAI0nhcbc-unsplash.jpg"
/>
<CardWithPhoto
title="Jeffrey"
description="Program Manager" …
```
> create CardWithPhoto component

- components/cards/ListItemWithImage.tsx
- theme/theme.ts
Create `ListItemWithImage` component. This component corresponds to the List Item with Pic component from the [Figma prototype](https://www.figma.com/file/vs1l6ERmi4AqYjxBBK9gDJ/Style-Guide-%26-Prototypes?type=design&node-id=465%3A41955&t=jGIhQj3fZ5tfrwxj-1)
Create component for new Open Seattle website
Import `ListItemWithImage` and test on any page. Save image to public folder. 
```
import * as React from 'react'
import Box from '@mui/material/Box'
import List from '@mui/material/List'
import DataObjectIcon from '@mui/icons-material/DataObject'
import CampaignIcon from '@mui/icons-material/Campaign'
import NoteAltIcon from '@mui/icons-material/NoteAlt'
import ListItemWithImage from 'components/cards/ListItemWithImage'
export default function BasicList() {
return (
<Box
sx={{
boxSizing: …
```
> Create ListItemWithImage component

- components/cards/CardEvent.tsx
- components/cards/CardGridContainer.tsx
- components/cards/CardJob.tsx
- components/cards/CardLeft.tsx
- components/cards/CardProject.tsx
- components/cards/StateButton.tsx
- components/filters/SearchToggle.tsx
- pages/volunteer.jsx
- styles/global.css
- theme/theme.ts
Created `CardLeft` and `CardJob` components, which are the last components left! 
I also made some small changes to other components that I meant to do in their original PRs-- 
- `CardProject` takes props for image src and alt 
- `CardGridContainer` takes an optional prop for number of columns
I noticed that the job cards aren't actually in the final prototype? I decided to make a quick one anyway, but I think it's something to check in about with designers.
Paste the following into any page!
imports:
```jsx
import CardGridContainer from 'components/cards/CardGridContainer'
import CardRowContainer from '../components/cards/CardRowContainer';
import CardJob from '../components/cards/CardJob'
import CardLeft from '../components/cards/CardLeft'
import …
```
> Created components: left-aligned card, job description card 

- assets/events.json
- components/cards/CardEvent.tsx
- pages/api/EventsService.ts
- pages/events_new.tsx
> Implement events page
> Need way to generate list of events without recoding
> Externalized events
> Small cleanups: fix bgColor & used CardRowContainer
> Externalized events; fix background color

- components/CommonHeader.tsx
Added more padding, made logo link to the homepage, and made sure mobile menu opens in the tablet view.
To address Kylie's feedback, make it look nicer!
Before:
After:
> Header design fixes

- components/CommonFooter.tsx
- pages/_app.tsx
> changed name@example.com to info@openseattle.org
> Use the correct emails
> replaced name@ with info@

- pages/404.tsx
> Incorporated latest design updates.
> Match spec and make responsive
> 404 page design & responsive updates

- components/CommonFooter.tsx
- pages/project_cadre.tsx
* Added link to home for logo in a footer.
* Added mailto for Contact Us button in project cadre page.
Minor cosmetic adjustments to address inconsistencies.
Checked it locally, it works as expected.
> Added links for logo in footer and Contact Us in project cadre.

- pages/volunteers.tsx
Updated Volunteer Agreement to the Latest Version
Updated Volunteer Agreement to the Latest Version.
Refer to the revised version [here](https://digitalaidseattle.slack.com/archives/C04FK0XHZEG/p1694038421746119) 
Checked locally, it works as expected.
> Updated Volunteer Agreement

- pages/index.tsx
> Hiding the Support Us Card
> NRFPT
> removed support-us card

- pages/about.tsx
- pages/volunteers.tsx
Fixed 'View our Cadre' and 'Apply to volunteer' buttons
Routes were incorrect and led to 404.
Checked it locally, works as expected.
> Fixed 'View our Cadre' and 'Apply to volunteer' buttons

- pages/about.tsx
> move and rename cadre button
> site info clarity
> move and rename cadre button

- components/cards/CardProject.tsx
- pages/about.tsx
- pages/api/ProjectsService.ts
- pages/project_individual.tsx
- pages/projects.tsx
- sanity.config.ts
- sanity/schemas/dasProject.ts
- sanity/schemas/index.js
- types.d.ts
> Updated Sanity to manage products information
> Allow dynamic updates to projects
> use CMS to manage projects list

- components/CommonFooter.tsx
- pages/index.tsx
- pages/partners.tsx
- pages/volunteers.tsx
- Unified headers on About and Volunteers page.
- Updated LinkedIn link.
- Undated reference on Partners page.
> Fix inconsistencies. 
> Verified locally, works as expected.
> Fixes of minor inconsistencies

- pages/project_individual.tsx
Unified headers on a project page.
Refer to the [task](https://github.com/orgs/openseattle/projects/1/views/2?pane=issue&itemId=39871521) and [design](https://www.figma.com/file/vs1l6ERmi4AqYjxBBK9gDJ/Style-Guide-%26-Prototypes?type=design&node-id=373-476&mode=design&t=z7iXx9wg9mBuNmlS-0)
Run it locally, displays as expected.
> Unified headers on a project page.

- pages/project_individual.tsx
> Fix for Impact section
> Bug in rendering
> Increase use of sub-components, reuse potential, reduce bugs
> fix impact by intrducing BodyTextSection

- pages/project_individual.tsx
> Fix capitalization
> jeff is lame.
> fix current team

- pages/volunteers.tsx
> Wording changes to volunteer
> Change to "Read our oath"
> Change to "You dedicate 4 hours a week for at least 6 months..."
> Updates to volunteers pages

- components/cards/CardLeft.tsx
- pages/partners.tsx
> Partners Page: update text in process and expectations sections
> Refer to [task](https://github.com/orgs/openseattle/projects/1/views/2?pane=issue&itemId=40110110) 
>  ![Screenshot 2023-09-28 at 15 40 26](https://github.com/openseattle/open-seattle-website/assets/58673729/e52b050f-71d0-4076-9e6e-e2c40a7b8ab8)
> Partners Page: update text in process and expectations sections

- pages/about.tsx
> Text in "What we do" & "Degrees" sections
> For clarity
> About page: Changes to text

- pages/volunteers.tsx
> Volunteer page: updated text under step 3 in 'The process' section.
> Per request, refer to [task](https://github.com/orgs/openseattle/projects/1?pane=issue&itemId=40211953) 
> Checked it locally.
> Volunteer page: updated text under step 3 in 'The process' section.

- pages/events.tsx
> Events page: updated text
> [Task](https://github.com/orgs/openseattle/projects/1/views/2?pane=issue&itemId=40212790) 
> Checked it locally.
> Events page: updated text

- pages/volunteers.tsx
> background color change
> To match spec
> Volunteers bckgnd

- components/RolesSection.tsx
- components/list/ListItemWithIcon.tsx
- pages/project_individual.tsx
> Extract roles-section
> To allow reuse of section in volunteers
`<RolesSection
title="Current volunteer openings"
roles={[]}
showLink={true}
columns={2} >
<Typography variant="bodyLarge" 
marginTop={'2rem'} textAlign={'center'}>All of our volunteers are vetted for experience, and sign a volunteer agreement before commencing work with Digital Aid Seattle.</Typography>
</RolesSection>`
> extract roles section

- components/CommonHeader.tsx
- components/RolesSection.tsx
- components/style-utils.tsx
- pages/api/VolunteerService.ts
- pages/project_individual.tsx
- pages/volunteers.tsx
> Reuse roles section
> match spec; avoid using Airtable embed
> extract style-utils
> Volunteer page uses roles list

- pages/privacy.tsx
> Change background color
> Fix title
> Add page headline
> Match design spec
> edit privacy page

- pages/volunteers.tsx
> Added padding
> To match spec
> added padding to volunteer page

- components/cards/CardEvent.tsx
> Check for empty properties in events
>  So the screen renders with poorly managed data
> check for null properties

- components/CommonHeader.tsx
- theme/theme.ts
> Fix high-light behavior in header button
> Meet design spec
> theme override for success.  Might not be the best solution
> Corrected header buttons per spec

- components/ProjectComponents.tsx
- pages/_app.tsx
- pages/about.tsx
- pages/cadre.tsx
- pages/project_individual.tsx
> Copied project_individual into a new page
> Moved shared components into separate file
> Sets up changes to support varying behavior between cadre and projects (i.e.. pull data from different source, show alumni, remove duplicate text found in rest of website)
> simple copy

- pages/_document.tsx
> Fix typo in code
> Use correct URL
> fix missing asset

- components/ProjectComponents.tsx
- components/RolesSection.tsx
- pages/api/AirtableService.ts
- pages/api/ProjectsService.ts
- pages/api/VolunteerRoleService.ts
- pages/cadre.tsx
- types.d.ts
> Use Airtable as data source for cadre
> Sorted by "First Name"
> Single source of truth
> Devs need to add env var NEXT_PUBLIC_AIRTABLE_TABLE_PEOPLE_REFERENCE
> Use Airtable as data source for cadre

- components/CommonHeader.tsx
- components/cards/CardEvent.tsx
- components/cards/CardReservation.tsx
- pages/_app.tsx
- pages/api/EventsService.ts
- pages/event.tsx
- sanity/schemas/osEvent.ts
- types.d.ts
> Created single event page
> Sanity updates
> Navigation changes (includes some small fixes)
> Need more Sanity updates
> Need Airtable event registration
> Need mobile fixes
> DAS needs a detailed page for events
> Event Page : Basic navigation and page layout

- components/layouts.tsx
- pages/cadre.tsx
- pages/events.tsx
- pages/project_individual.tsx
- pages/projects.tsx
- pages/volunteer_role.tsx
- pages/volunteers.tsx
- styles/global.css
> Loading context
> Standardize how the progress indicator is displayed
> add this: const { setLoading } = useContext(LoadingContext);
> added loading context

- components/layouts.tsx
- pages/api/ProjectsService.ts
- pages/cadre.tsx
- pages/events.tsx
- pages/project_individual.tsx
- pages/projects.tsx
- pages/volunteer_role.tsx
- pages/volunteers.tsx
- styles/global.css
> pulling up changes
> Should simplify reviewing single-event-page work
> Pulling main into single-event-page

- pages/event.tsx
> added better spacing

- components/cards/CardEvent.tsx
- pages/event.tsx
- pages/volunteers.tsx
- sanity/schemas/osEvent.ts
> volunteer typo
> event image fix
> corrected event card button
>  to match design spec
> Small fixes

- components/layouts.tsx
- pages/cadre.tsx
- pages/event.tsx
- pages/events.tsx
- pages/project_individual.tsx
- pages/projects.tsx
- pages/volunteer_role.tsx
- pages/volunteers.tsx
> Having some fun, trying a LoadingBlock
> A little more flexible
> trying a loading block

- components/CommonFooter.tsx
- components/cards/CardEvent.tsx
- components/cards/CardProject.tsx
- theme/theme.ts
- match hover state of project and event cards to spec
- adjust size of logo in footer to match header
- address feedback from Yulia and Grace
hover effect is now a subtly darker shadow:
footer logo at 120px to match header:
> small styling edits to cards and footer

- components/CommonHeader.tsx
- pages/_document.tsx
- styles/global.css
- header is now sticky!
- had to remove some global css to get it to work, which doesn't appear to have side effects.
> implement sticky header

- components/ProjectComponents.tsx
- pages/project_individual.tsx
> Added breadcrumbs to project page
> Added about section to project page
> Consistency
> Truncation on project card suggests placing about on project page
> added about and breadcrumbs

- package.json
- pages/_app.tsx
- yarn.lock
> Add analytics package
> To capture web traffic info
> We will need to enable analytics on Vercel when deployed
> vercel analytics

- components/cards/CardProject.tsx
- pages/api/ProjectsService.ts
A partner may be added to AirTable without a logo. The website should handle that situation
To display without failing
> handle empty logo

- README.md
- components/CommonFooter.tsx
> Update GitHub links
> Correctness matters.
> change open-seattle to digital-aid-seattle

- README.md
Fixed links to the partner and volunteer pages.
> Update README.md - fixed partner & volunteer links

- README.md
Added a space and removed a slash in a link.
> Minor changes in README file

- components/CommonHeader.tsx
- components/ProjectComponents.tsx
- components/RolesSection.tsx
- components/cards/CardEvent.tsx
- pages/api/ProjectsService.ts
- pages/event/[...slug].tsx
- pages/project/[...slug].tsx
- pages/volunteer/[...slug].tsx
> Use path params instead of search params
example:
-  /event/yolk-feb-2024  replaces /event?name=yolk-feb-2024
- /project/recC6yznqhaY9usSm replaces /project?project=recC6yznqhaY9usSm
- /volunteer/hr-generalist replaces  /volunteer?role=hr-generalist
> Allows better reporting in page views in analytics
> Shorter URLs
> path params

- pages/cadre.tsx
> Enable role linking from cadre page
> Seamus requested that linking from cadre page to volunteer roles be permitted.
> allow roles linking from cadre page

- pages/cadre.tsx
> Status change in AirTable "ongoing" -> "Cadre"
> To see some faces
> Fix cadre page

- pages/api/FaqService.ts
- sanity.config.ts
- sanity/schemas/dasFaq.ts
- sanity/schemas/dasQandA.ts
- sanity/schemas/index.js
- types.d.ts
- Sanity schema updates
- Website types created
> Support faq initiatives
> sanity driven data

- components/CommonHeader.tsx
> Use status flag in useFeature hook to delay menu creation
> Hides lag when getting state from Sanity
> use fetched status

- components/CommonHeader.tsx
> Fix to header where there was excessive re-render calls
> Improve performance
> Fix for excessive rerenders

- sanity.config.ts
- sanity/schemas/dasTestimonial.ts
- sanity/schemas/index.js
- types.d.ts
> Sanity schema updates for testimonials
> To allow more frequent updates to testimonial section
> Open up possibilities for different presentations
> sanity schema for testimonials

- pages/partners.tsx
> Update DAS Airtable partner form link
>To fulfill request from operations
> new partner from address

- .gitignore
- services/ProjectsService.ts
> The Airtable Staffing Needs table is being used for Cadre support.  The filter for ventures needed adjusted.
> Present accurate information.
> Fix for Project Page

- pages/support_us.tsx
addressing changes and adding responsive components
> Addressing comments

- components/email-form/EmailFormContainer.tsx
- package.json
- pages/api/newsletter.ts
- yarn.lock
> Revised to use BREVO v3 API
> update to API usage
> Revised to use BREVO v3 API

- components/MastheadWithImage.tsx
- pages/index.tsx
Update MastheadWithImage to include img text as alt for accessibility.
https://digital-aid-seattle.atlassian.net/browse/DW-21
_Please replace this line with instructions on how to test your changes, as well as any relevant images for UI changes._
> Update component to include img text as alt

- pages/support_us.tsx
- styles/global.css
- yarn.lock
- used the responsive features of react-slick carousel
- small refactor for arrows
> made carousel responsive

- components/cards/CardOne.tsx
- package.json
- pages/support_us.tsx
- styles/global.css
- yarn.lock
add a carousel to support us testimonials
to better display information on the page
some issues with resizing at the lower levels
> Support us carousel

- components/cards/CardQuote.tsx
- pages/support_us.tsx
- enforced size based on breakpoints
I had to use a iPhone simulator to display the problem
> fix slider

- pages/volunteer/[...slug].tsx
Updated line height
](https://digital-aid-seattle.atlassian.net/browse/DW-110)
> fixed line height
