digitalaidseattle/digital-aid-seattle-website

components/list/ListItemWithIcon.tsx, theme/theme.ts
Create `ListItemWithIcon` Component. Added style override for MuiListItem.
Create `ListItemWithIcon` component for new Open Seattle Website
Import `ListItemWithIcon` component and test on page. 
```
import * as React from 'react'
import Box from '@mui/material/Box'
import List from '@mui/material/List'
import DataObjectIcon from '@mui/icons-material/DataObject'
import CampaignIcon from '@mui/icons-material/Campaign'
import NoteAltIcon from '@mui/icons-material/NoteAlt'
import ListItemWithIcon from 'components/list/ListItemWithIcon'
export default function BasicList() {
return (
<Box
sx={{
boxSizing: 'border-box',
width: '100%',
maxWidth: 360,
flex: '1',
minWidth: { xs: '100%', sm: 'min-content' },
boxShadow:
'0px 4px 8px 2px rgba(52, 61, 62, 0.04), 0px 2px 4px rgba(52, 61, 62, 0.04)', …
```
=> Create ListItemWithIcon component

components/list/ListItemWithIcon.tsx
Previous [Create ListItemWithIcon Component PR](https://github.com/openseattle/open-seattle-website/pull/24) used internal designColor instead of useTheme. Fixing in this PR.
useTheme so that future changes to palette will be automatically applied
Import `ListItemWithIcon` component and test on page.
```
import * as React from 'react'
import Box from '@mui/material/Box'
import List from '@mui/material/List'
import DataObjectIcon from '@mui/icons-material/DataObject'
import CampaignIcon from '@mui/icons-material/Campaign'
import NoteAltIcon from '@mui/icons-material/NoteAlt'
import ListItemWithIcon from 'components/list/ListItemWithIcon'
export default function BasicList() {
return (
<Box
sx={{
boxSizing: 'border-box',
width: '100%',
maxWidth: 360,
flex: '1',
minWidth: { xs: '100%', sm: …
```
=> Update ListItemWithIcon component styling

components/CommonHeader.tsx, components/cards/CardRowContainer.tsx, components/list/ListItemWithIcon.tsx, pages/about_new.tsx
Respond to design feedback from Kylie in https://www.figma.com/file/Qa1UC7cGLmEXbWXuRmgjpO/OS-Website-Annotations?type=whiteboard&node-id=136-244&t=b0ZTHbieDxjcHqTm-0
One of the change is align the hero section to the common header. I made changes to the header so that should fix places like volunteer page and other places that use a similar setup for hero section as well.
Need to touch up before we can publish this page.
- useMediaQuery different API such as 'up' and 'down' to get range of screensize. so convenient! 
- some feedback were partially addressed when @mistyb01 pushed the card container changes #44
- I added some small changes to listitem so that the text doesn't go out of the boxes. 
Please see vercel. 
https://open-seattle-website-git-santina-polishabout-dev-openseattle.verce …
=> Polish about page based on feedback

components/CommonFooter.tsx, pages/index.tsx
Fixed “How can you help” -> ‘How you can help” in a footer
> Fixed a typo.
=> Fixed “How can you help” -> ‘How you can help” in a footer

components/cards/CardWithPhoto.tsx, components/list/ListItemWithIcon.tsx, pages/project_cadre.tsx
- Updated 'roles needed' section with roles DAS actually needs!
- Team section looks better after making it four columns, like the figma.
- Fixed broken 'apply to volunteer' link
Address design feedback, update with real content.
The 'roles needed' section is static for now, i.e. not integrated with Sanity.
Side note, for implementing this with Sanity- I'm thinking having a set of predefined role titles, so they can be selected from a dropdown in Sanity, would be nice to have. And in our code, we could associate each role with a material UI icon.
card grid now has four columns at the widest breakpoint:
populated the …
=> Cadre page: updated 'roles needed', minor design fix

pages/project_individual.tsx, sanity/schemas/dasProject.ts
> Add QA specialist To List of Roles with icons and title
> To match internal Airtable data
> Need to update CMS to add "qaSpecialist" for appropriate project
=> Add QA specialist To List of Roles

components/CommonFooter.tsx
LinkedIn and Github footer links open in a new browser tab.
Refer to [task](https://github.com/orgs/openseattle/projects/1/views/2?pane=issue&itemId=39877322) 
Checked it locally, works as expected.
=> Footer links open in a new browser tab

components/CommonFooter.tsx
> Removed support us section  footer
> not ready to support it
large:
medium:
small:
=> remove support us from footer

components/list/ListItemWithIcon.tsx, pages/about.tsx
Slight edits to layout and cards to make it more readable on smaller devices. 
before:
after:
=> Responsive fixes for About page

components/RolesSection.tsx
Fix page responsiveness on the Volunteer, Cadre, and Individual Project pages. (addresses issue #6873 on airtable)
For improved formatting on mobile screens.
I decided to change the grid behavior at three separate breakpoints:
- On Desktops the formatting remains as it was (three columns)
- On tablets/medium-sized screens the number of columns changes to two
- On mobile devices, the number of columns is reduced to one and the space between items in the column is decreased.
Mobile
Tablet
Desktop
=> fix: Improve responsiveness of roles section

pages/api/ProjectsService.ts
Fix error created by missing team member photo on Cadre page
Missing photo created an error and prevented rendering the team members
If a photo is not part of the object returned by air table, the service returns undefined.
In[ ProjectComponents.tsx](https://github.com/openseattle/open-seattle-website/blob/033205882fb6f7b3248a42d52f7ebfa6295ad700/components/ProjectComponents.tsx#L341), this undefined value is resolved with a placeholder image.
=> fix: Handle empty photo on cadre team

components/cards/CardEvent.tsx, components/cards/CardProject.tsx
- Addressing Grace's design edits ([figma link](https://www.figma.com/file/vs1l6ERmi4AqYjxBBK9gDJ/Style-Guide-%26-Prototypes?node-id=1114%3A39079&mode=dev)), where the action buttons on the project and event cards are removed, and the whole card is made clickable.
- Also fixed the mobile breakpoint on the event cards, and refactored a bit there
Used [CardActionArea](https://mui.com/material-ui/react-card/#primary-action) from MUI to make the card clickable. I like the built-in hover effect!
Bummed that I couldn't make the cards keyboard accessible, would like to figure that out. Adding `tabIndex` or even wrapping the whole card with a link did not work :/
=> implement ux changes for project and event cards

components/cards/CardProject.tsx
> Capping the length  of description to 4 lines
> limit length of card to fit more cards on a page
=> cap description length to 4 lines

components/CommonHeader.tsx, components/MobileMenu.tsx
- implement figma design of the mobile navigation.
- mostly for fun. a nicer experience for phone users 
- created `MobileMenu` component, which takes in links in its `children` prop
- wrapped `CommonHeader` in a sticky-positioned `Box` to fix the issue with z-index and make the transition effect possible 
=> mobile slide-out menu

pages/events.tsx, sanity/schemas/osEvent.ts, types.d.ts
upcoming events and past events are rendered in separate sections.
just did some simple array filtering on the airtable data!
per design spec; to separate upcoming and past events.
how it looks without upcoming events (like current website):
mocking multiple events
=> events page: section for past events

components/cards/CardProject.tsx
> Project card log image fix
> Removed border around image
> Partner logos come in many sizes.  Doing our best to make them fit
=> fit partner image to fit in card

components/HeaderWithImage.tsx, components/ProjectComponents.tsx, components/cards/CardProject.tsx, pages/event.tsx
- Non-square logos will be centered in a white container.
- No more overlapping of elements on smaller screen sizes.
- More consistency in the heading section height--only expands as needed.
- Responsiveness
- Layout is more resilient: can handle long titles and different logo sizes without looking ugly.
- `DesktopHeader` now has a min height, instead of its size being determined only with vertical padding from its children. This means that the heading area will only grow as needed, which gets rid of the large amount of extra space that was above the multi-line titles. See screenshots!
- Since the single event and project pages have that same green heading with …
=> fix responsiveness on project pages

pages/support_us.tsx
> Provided a reroute when the feature flag is disabled.
> To prevent user from viewing the support us page if the feature is disabled.
=> add feature flag to support page

components/CommonHeader.tsx
- minor fix, where a dark overlay div appears under the mobile menu when toggled.
- to address usability feedback, which was to prevent misclicks when interacting with menu.
=> add dark overlay when menu is toggled

components/email-form/EmailFormContainer.tsx
> The label for the newsletter signup was being displayed
> looks bad otherwise
before:
after:
=> fix common footer
